### ISSUE TITLE
PyHSPlasma: Crashes when loading and unloading converted Minkata files

### ISSUE THREAD

**Issue by diafero** [H-uru/libhsplasma#38]
The following small script triggers a segfault when run in the Uru:CC directory:

```
import PyHSPlasma
plResMgr = PyHSPlasma.plResManager()

for file in ("Minkata_District_minkCameras.prp",
			 "Minkata_District_minkExteriorDay.prp"):
	print "loading",file
	page = plResMgr.ReadPage("dat/"+file)
	print "unloading",file
	plResMgr.UnloadPage(page.location)

```

The program prints the following output:

```
loading Minkata_District_minkCameras.prp
unloading Minkata_District_minkCameras.prp
loading Minkata_District_minkExteriorDay.prp
Segmentation fault
```

The crash does not happen if I just load `minkExteriorDay.prp`.

The backtrace is
```
#0  0x00007ffff642a10c in plSceneObject::addTarget (this=0x1d4df80, obj=<optimized out>) at /home/r/src/uru/libhsplasma/core/PRP/Object/plSceneObject.cpp:28
#1  0x00007ffff63efbe4 in plKeyData::setObj (this=0x1f6f920, obj=obj@entry=0x157f7c0) at /home/r/src/uru/libhsplasma/core/PRP/KeyedObject/plKey.cpp:83
#2  0x00007ffff63ef1b4 in hsKeyedObject::read (this=0x157f7c0, S=S@entry=0x1533300, mgr=mgr@entry=0xa12580) at /home/r/src/uru/libhsplasma/core/PRP/KeyedObject/hsKeyedObject.cpp:36
#3  0x00007ffff642cc60 in plSynchedObject::read (this=0x157f780, S=S@entry=0x1533300, mgr=mgr@entry=0xa12580) at /home/r/src/uru/libhsplasma/core/PRP/Object/plSynchedObject.cpp:21
#4  0x00007ffff63fea58 in plMultiModifier::read (this=0x157f720, S=S@entry=0x1533300, mgr=mgr@entry=0xa12580) at /home/r/src/uru/libhsplasma/core/PRP/Modifier/plModifier.cpp:51
#5  0x00007ffff6401aad in plPythonFileMod::read (this=0x157f6d0, S=0x1533300, mgr=0xa12580) at /home/r/src/uru/libhsplasma/core/PRP/Modifier/plPythonFileMod.cpp:229
#6  0x00007ffff649acbc in plResManager::ReadCreatable (this=this@entry=0xa12580, S=S@entry=0x1533300, canStub=canStub@entry=true, stubLen=stubLen@entry=417) at /home/r/src/uru/libhsplasma/core/ResManager/plResManager.cpp:619
#7  0x00007ffff649bb27 in plResManager::ReadObjects (this=this@entry=0xa12580, S=S@entry=0x20c6b40, loc=...) at /home/r/src/uru/libhsplasma/core/ResManager/plResManager.cpp:514
#8  0x00007ffff649d990 in plResManager::ReadPage (this=0xa12580, filename=<optimized out>, stub=<optimized out>) at /home/r/src/uru/libhsplasma/core/ResManager/plResManager.cpp:168
#9  0x00007ffff68fbe78 in pyResManager_ReadPage (self=0x7ffff7f5c228, args=<optimized out>) at /home/r/src/uru/libhsplasma/Python/ResManager/pyResManager.cpp:159
```

I am pretty sure this used to work in earlier versions - I am still trying to figure out when it broke.

**Comment by diafero** [comment]
This bug is no longer present.
